### ISSUE TITLE
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by BuptStEve** [zhhlwd/vuepress-theme-indigo-material#5]
**问题**
```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.  vue.min.js:6 
    at Object.appendChild (https://cdn.bootcss.com/vue/2.6.4/vue.min.js:6:40599)
    at v (https://cdn.bootcss.com/vue/2.6.4/vue.min.js:6:56684)
    at f (https://cdn.bootcss.com/vue/2.6.4/vue.min.js:6:56315)
    at h (https://cdn.bootcss.com/vue/2.6.4/vue.min.js:6:56767)
    at O (https://cdn.bootcss.com/vue/2.6.4/vue.min.js:6:60109)
    at O (https://cdn.bootcss.com/vue/2.6.4/vue.min.js:6:60044)
    at O (https://cdn.bootcss.com/vue/2.6.4/vue.min.js:6:60044)
    at a.__patch__ (https://cdn.bootcss.com/vue/2.6.4/vue.min.js:6:60467)
    at a.e._update (https://cdn.bootcss.com/vue/2.6.4/vue.min.js:6:33990)
    at a.r (https://cdn.bootcss.com/vue/2.6.4/vue.min.js:6:67552)
```

**复现步骤**

1. 访问 https://zhhlwd.github.io/
2. 点击 时间归档
3. 点击刷新

![image](https://user-images.githubusercontent.com/11501493/53283787-9535ff00-3786-11e9-92ca-47d4d9a632aa.png)

**Comment by zhhlwd** [comment]
已经修复了，是因为vuepress的ssr后导致vue更新视图时报错，请下载1.0.5版本

**Comment by icemirror** [comment]
> 已经修复了，是因为vuepress的ssr后导致vue更新视图时报错，请下载1.0.5版本

@zhhlwd 你好, 打扰了, 我也用了vuepress做静态文档, 也遇到了这个问题, 可以请问一下这个问题是怎么导致的, 又需要如何解决呢, 我看了你的commit 不是很懂你的用意, 如果你有时间的话, 可以分享一下解决思路吗 🙏

**Comment by zhhlwd** [comment]
> > 已经修复了，是因为vuepress的ssr后导致vue更新视图时报错，请下载1.0.5版本
> 
> @zhhlwd 你好, 打扰了, 我也用了vuepress做静态文档, 也遇到了这个问题, 可以请问一下这个问题是怎么导致的, 又需要如何解决呢, 我看了你的commit 不是很懂你的用意, 如果你有时间的话, 可以分享一下解决思路吗 🙏

刚开始我的主题除了首页外其它页的内容是在线上生成的，当vuepress预渲染时只渲染首页的内容，分类页等等的HTML几乎是没有内容的，当在线上用户浏览器第一次访问的就是那些没有经过预渲染的页面时，就会报错，后来让所有的页面的有机会预渲染后，就不会报错了。这应该是ssr的一个常见问题，在Nuxt.js的issue中也经常出现，解决方法是让vuepress在预渲染成html时尽可能的把内容都写进html。

**Comment by icemirror** [comment]
> > > 已经修复了，是因为vuepress的ssr后导致vue更新视图时报错，请下载1.0.5版本
> > 
> > 
> > @zhhlwd 你好, 打扰了, 我也用了vuepress做静态文档, 也遇到了这个问题, 可以请问一下这个问题是怎么导致的, 又需要如何解决呢, 我看了你的commit 不是很懂你的用意, 如果你有时间的话, 可以分享一下解决思路吗 🙏
> 
> 刚开始我的主题除了首页外其它页的内容是在线上生成的，当vuepress预渲染时只渲染首页的内容，分类页等等的HTML几乎是没有内容的，当在线上用户浏览器第一次访问的就是那些没有经过预渲染的页面时，就会报错，后来让所有的页面的有机会预渲染后，就不会报错了。这应该是ssr的一个常见问题，在Nuxt.js的issue中也经常出现，解决方法是让vuepress在预渲染成html时尽可能的把内容都写进html。

@zhhlwd  十分感谢! 已经解决了
